---
title: "Lab Manual Conservation Biology Fall 2020"
subtitle: "Conservation Biology Fall 2020"
author: "Shannon J. O'Leary"
date: "`r Sys.Date()`"
knit: "bookdown::preview_chapter"
output:
  msmbstyle::msmb_html_book:
    highlight: tango
    toc: TRUE
    toc_depth: 1
    split_by: chapter
    margin_references: FALSE
    css: msmb.css
bibliography: labmanual.bib
link-citations: yes
---

```{r include=FALSE}

library(msmbstyle)

# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion('msmbstyle'))


options(htmltools.dir.version = FALSE)

```

# Overview {-}

This is the lab manual for Conservation Biology (BI328). It will be continuously updated throughout the semester, generally there are no pre-labs (just homework, you can't win).  
For the most part an electronic copy (on a laptop or tablet) is sufficient, at times you may be instructed to print a data or worksheet for lab.

## The Basics {-}

**Lab times**

Wednesday 1:30 - 4:30pm (GOUL3102)  
*Be on time, arriving > 5 minutes late will be considered an unexcused absence.*

<br>


**BYOD: Bring your own device (to lab)**

You are required to bring your laptop for use during lab; a tablet will not be sufficient to participate though you are welcome to bring an additional device to have an extra screen to follow along an electronic version of the lab manual. Make sure to have a power cable and/or fully charged battery!

<br>


## Lab homework/reports {-}

You will be receiving lab homework in some format almost every lab, part of the assignments will be completed in lab, other parts your will finish on your own time. Make sure you start early enough to get help if necessary.  

**Due by the following Wednesday 12pm** unless otherwise specified.  
*No late or incomplete homework will be accepted or receive credit.*


### Due Wednesday, Sept. 2nd {-}

Complete lab 3 ([tidyverse tutorial](https://labmanual.netlify.app/welcome-to-the-tidyverse.html)) and upload the knitted^[Remember, in order to knit a document all the code chunks must be able to run properly - so make sure that you delete any "experimental code chunks" (e.g. if you tried something that didn't work).] `html` document through Canvas (`HW-2`).


<br>

### Due Wednesday, Aug. 26th {-}

Introduce yourself in the  `#general` slack channel:

* Give your name, major, year
* Tell us what you are hoping to get out of this class^[If it's 'check it off my list to graduate' - that's fine, we'll try to make this class more than a check mark!]
* Explain which category you fit in best as a "conservation biologist": Preservationist, Resource Management, Environmentalism (Activism), Environmental Science, or Ecologist. You don't have to choose just one.

Find a field buddy and sign up on the spreadsheet (find the link in the  `#field-outings` slack channel) for two visits to each site.

Go back over Chapter 2 and 3 so you are comfortable with the layout of Rstudio, creating a project directory, and what an Rmarkdown document looks like - play with it a little bit, we will be doing this throughout the semester.

